### ISSUE TITLE
Generating Code for mpx_network_object.rda

### ISSUE THREAD

**Issue by mark-orr** [CDCgov/mpx_networkmodel_mmwr#1]
It would be very useful to include the code that generated the netest class object mpx_network_object.rda .  This would better make the full codebase replicable.

**Comment by EmilyPo** [comment]
We have added two scripts ("setup_functions" and "fit_networks") that you will need to estimate the set of networks used in this project.

**Comment by mark-orr** [comment]
Very helpful.  Thanks.


From: Emily Pollock ***@***.***>
Date: Monday, September 19, 2022 at 2:42 PM
To: CDCgov/mpx_networkmodel_mmwr ***@***.***>
Cc: Orr, Mark (mo6xj) ***@***.***>, Author ***@***.***>
Subject: Re: [CDCgov/mpx_networkmodel_mmwr] Generating Code for mpx_network_object.rda (Issue #1)

We have added two scripts ("setup_functions" and "fit_networks") that you will need to estimate the set of networks used in this project.
